services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgresqldocker'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8000:80'
    depends_on:
      - postgres

volumes:
  postgres_data:   