spring:
    application:
        name: razerGold
    
    datasource:
        url: jdbc:postgresql://dpg-d0n12n3ipnbc73dlejk0-a:5432/razerdb
        username: postgresql
        password: f1gAlLtQKijFvL9ajDN8i1oxnBBt6BmN
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true


    cloud:
        config:
            enabled: false


    h2:
        console:
            enabled: false

    jmx:
        enabled: false